Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora38"
  config.ssh.insert_key = false

  config.vm.hostname = "jirasek"

  config.vm.network "public_network",
                    bridge: "Intel(R) 82579LM Gigabit Network Connection",
                    ip: "192.168.1.100" # Nastavte pevnou IP adresu podle vaší sítě

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

  config.vm.provision "shell", path: "install-zabbix-agent2.sh"
end